apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - quotas.yaml
  - artifact-services.yaml
  - artifact-gateway.yaml
  - build-sandbox-policy.yaml
  - build-controller.yaml
  - network-policies.yaml
  - cilium-policies.yaml
